@startuml

title System Context diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(specialist, "Инженер", "Специалист по установке и настройке оборудования")
Person(user, "Пользователь", "Пользователь системы Умный Дом")

System(Server, "Умный дом", "управление отоплением и сбор значений температуры в доме")
System_Boundary(House, "Дом") {
    System_Ext(sensor, "Датчик", "замеряет температуру")
    System_Ext(relay, "Реле", "управляет отоплением")
}

Rel(user, Server, "просматривает и управляет температурой в своих домах")
Rel(specialist, sensor, "устанавливает, обслуживает")
Rel(specialist, relay, "устанавливает, обслуживает")
Rel(specialist, Server, "добавляет в систему устройства, дома")
Rel(Server, sensor, "получает значения температуры от")
Rel(Server, relay, "управляет отоплением посредством")

@enduml